export const aboutContent = {
  title: "An online bar for adults.",
  paragraphs: [
    "Druncord exists because most online communities forgot how to feel like places. Plenty of servers can accumulate members. Plenty can generate notifications. Very few feel like walking into a room where somebody is actually there, the conversation is already moving, and you can decide whether to jump in or lean on the wall for a minute. That gap is what Druncord is built to fill.",
    "At its core, Druncord is an 18+ Discord community designed like an online bar. The point is voice, not clutter. People come in to talk, unwind, play the occasional game, listen to music, or just be around other adults after the day is over. Some nights are loud. Some nights are slower. Either way, the room matters more than the feed. It is social on purpose, not because a bot posted enough prompts to keep a channel alive.",
    "What makes it different from a typical gaming or bot server is mostly what it does not do. It is not built around patch notes, ranking systems, role menus, or endless dead-end text channels. The server is voice-first because voice is where tone lives. You hear whether a room is warm, awkward, funny, tired, sharp, or worth sticking around for. That is hard to fake, which is part of the appeal.",
    "The regulars are adults with jobs, routines, weird schedules, and enough life behind them to want a better kind of internet hangout. Some show up with a drink. Some do not. Some are there to tell stories, some to listen, some to play games, and some to let the night run a little longer before logging off. The overlap is simple: people want company that feels human and unforced.",
    "Druncord also works because it does not pretend to be for everybody. It is social, not gaming-first. Drinking is part of the culture, but not a membership requirement. The tone is dry, lived-in, and adult. There is moderation, but it is there to keep the room usable, not to turn every interaction into policy theater. If somebody consistently makes the place worse, staff deal with it and move on.",
    "The people running it are, by design, not trying to sound like corporate community managers. A few adults wanted a better bar, so they built one. That means the standards are practical. The rules are written in plain English. The events are there to give the room a little shape, not to fill a spreadsheet. The welcome is real, but nobody is going to perform fake enthusiasm at the door.",
    "If that sounds unusually simple, good. That is the idea. Druncord is for adults who miss the feeling of a place with regulars, rhythm, and conversation. A room you can drop into late, hear actual voices, and decide to stay because it already feels lived in.",
  ],
};
